###############
# Config for the parameters for training, model, data, etc.
###############

base_config: &BASE_CONFIG
    ## parameters
  random_seed: 42

  phase: 3 # simply easier for model naming, still T=0
  run_name: "3d_sweep_1000ep"
  n_vars: 3
  debug_mode: False

  ## model parameters
  mode: "hard" # "soft" or "hard" 
  inp_dim: 3
  nlayers: 6
  hidden: 32
  activation: "Tanh" # SiLU, Tanh, ReLU, Identity, SIREN, GELU, Mish
  w0: 30
  add_phi0: False
  k_val: 10
  use_m_loss: True
  update_m: False
  m_loss_m_value: 0.5

  ## normalisation
  norm_mode: "standardize"   # minmax or standardize
  standard_mean: 0.0
  standard_std: 1.0
  minmax_min: -1.0
  minmax_max: 1.0

  ## wandb parameters
  wandb_group: "week12jan"
  wandb_project: "mini_pinn"
  wandb_entity: "guzelmen_msci_project"

  ## optimizer parameters
  lr_type: "cosine" # constant, linear, linear with cosine decay...
  constant_lr: 1e-4
  start_lr: 1e-5
  end_lr: 5e-4
  lr_warmup_epochs: 100
  min_lr: 1e-5  # Minimum LR for cosine decay
  grad_clipping: False

  ## loss parameters
  loss_type: "mse" # might need to rethink if magnitude issues
  fmt_help: False
  loss_strategy: "fixed" # "fixed" or "adaptive"
  fmt_weights: {"residual": 1.0, "fmt": 1.0}
  cancel_c: False  # keep C factor in PDE (do not cancel)

  ## data parameters
  data_path: "data/phase_2_LOG500x_RED128alpha.pt"
  batch_size: 512
  shuffle_train: True

  ## training parameters
  stage: "train"
  epochs: 1000
  save_every: 100

  # saving
  plot_auto: True
  save_weights: True
  save_weights_every: 100
  pred_dir: "predictions"
  plot_dir: "plot_predictions"
  