###############
# Config for Phase 4: Temperature-dependent Thomas-Fermi
# Inputs: [x, alpha, T_kV]
# SMALL RANGE: alpha ~1-5, T 1-10 keV
###############

base_config: &BASE_CONFIG
    ## parameters
  random_seed: 42

  run_name: "GPU_adaptcosinenormal_5000ep_physweightsched"
  wandb_notes: ""
  ## wandb parameters
  wandb_group: "week09feb"
  wandb_project: "mini_pinn"
  wandb_entity: "guzelmen_msci_project"

  phase: 4 # temperature-dependent TF
  n_vars: 3  # network inputs
  debug_mode: False

  ## model parameters
  mode: "hard" # "soft" or "hard"
  inp_dim: 3  
  nlayers: 6
  hidden: 64
  activation: "SiLU" # SiLU, Tanh, ReLU, Identity, SIREN, GELU, Mish
  w0: 30
  add_phi0: False
  k_val: 10
  
  # m-weighted loss: multiplies residual by x^(0.5+m) on LHS, x^(1.5+m) on RHS
  # m=-0.5 is equivalent to no m-weighting (baseline)
  use_m_loss: True
  m_loss_m_value: -0.5  # sweep values: -0.5, 0, 0.5, 1.0

  ## normalisation (alpha)
  norm_mode: "standardize"   # minmax or standardize
  standard_mean: 0.0  # Will be computed from train data
  standard_std: 1.0   # Will be computed from train data
  minmax_min: -1.0
  minmax_max: 1.0

  ## normalisation (T) - computed from train data
  T_mean: 0.0
  T_std: 1.0

  ## optimizer parameters
  lr_type: "cosine" # constant, linear, cosine, cosine_restarts
  constant_lr: 1e-4
  start_lr: 1e-5
  end_lr: 5e-4
  lr_warmup_epochs: 200
  min_lr: 1e-5  # Minimum LR for cosine decay
  # cosine_decay_epochs: 2000  # Fixed cosine decay period (omit to use total_epochs - warmup)
  # cosine_restart_period: 500  # Epochs per cycle for lr_type="cosine_restarts"
  grad_clipping: True  # Clips to max_norm
  clip_value: 10.0

  ## loss parameters
  loss_type: "mse"
  # Residual normalization strategy for training
  # "coeff": divide by λ³/γ (current default)
  # "relative": divide by max(|LHS|, |RHS|) - per-sample relative error  
  # "rel_l2": divide by RHS L2 norm (over batch) - global relative L2 error"
  residual_norm_strategy: "rel_l2"
  
  fmt_help: False
  loss_strategy: "fixed" # "fixed" or "adaptive"
  fmt_weights: {"residual": 1.0, "fmt": 1.0}
  cancel_c: False

  ## hybrid training (data + physics loss)
  hybrid_training: True  # If True, combine PDE loss with data loss
  use_solver_data: True  # If True, load data in {inputs, targets} format
  data_loss_type: "rel_l2"  # options: "mse", "rel_l2"
  physics_loss_weight: 1.0  # Weight for PDE residual loss
  data_loss_weight: 10.0     # Weight for data MSE loss
  data_loss_step_epochs: 500
  hybrid_weight_strategy: "fixed"  # "fixed" or "adaptive"

  ## data parameters
  data_path: "data/phase_4_solver_inp&targets_smallrange.pt"
  batch_size: 2048
  shuffle_train: True

  ## training parameters
  stage: "train"
  epochs: 5000

  # saving
  save_preds: False
  save_every: 100
  plot_auto: False
  save_weights: True
  save_weights_every: 100
  pred_dir: "predictions"
  plot_dir: "plot_predictions"
