###############
# Config for Phase 4: Temperature-dependent Thomas-Fermi
# Inputs: [x, alpha, T_kV]
# SMALL RANGE: alpha ~1-5, T 1-10 keV
###############

base_config: &BASE_CONFIG
    ## parameters
  random_seed: 42

  phase: 4 # temperature-dependent TF
  run_name: "phase4_small_range_debug"
  n_vars: 3  # network inputs
  debug_mode: True

  ## model parameters
  mode: "hard" # "soft" or "hard"
  inp_dim: 3  
  nlayers: 6
  hidden: 64  # larger network for 3D input
  activation: "Tanh" # SiLU, Tanh, ReLU, Identity, SIREN, GELU, Mish
  w0: 30
  add_phi0: False
  k_val: 10
  use_m_loss: False
  update_m: False
  m_loss_m_value: 0.5

  ## normalisation (alpha)
  norm_mode: "standardize"   # minmax or standardize
  standard_mean: 0.0  # Will be computed from train data
  standard_std: 1.0   # Will be computed from train data
  minmax_min: -1.0
  minmax_max: 1.0

  ## normalisation (T) - computed from train data
  T_mean: 0.0
  T_std: 1.0

  ## wandb parameters
  wandb_group: "week19jan"
  wandb_project: "mini_pinn"
  wandb_entity: "guzelmen_msci_project"

  ## optimizer parameters
  lr_type: "cosine" # constant, linear, linear with cosine decay...
  constant_lr: 1e-4
  start_lr: 1e-5
  end_lr: 5e-4
  lr_warmup_epochs: 100
  min_lr: 1e-5  # Minimum LR for cosine decay
  grad_clipping: False

  ## loss parameters
  loss_type: "mse"
  fmt_help: False
  loss_strategy: "fixed" # "fixed" or "adaptive"
  fmt_weights: {"residual": 1.0, "fmt": 1.0}
  cancel_c: False

  ## data parameters
  # Phase 4 SMALL range: [x, alpha, T_kV] with 160x20x20 = 64k points
  data_path: "data/phase_4_small_range.pt"
  batch_size: 2048
  shuffle_train: True

  ## training parameters
  stage: "train"
  epochs: 10
  save_every: 100

  # saving
  plot_auto: False  # Phase 4 plotting TBD
  save_weights: False
  save_weights_every: 100
  pred_dir: "predictions"
  plot_dir: "plot_predictions"
