###############
# Config for the parameters for training, model, data, etc.
###############

base_config: &BASE_CONFIG
    ## parameters
  random_seed: 42

  phase: 2
  run_name: "firsttry_newpde"
  inp_dim: 2

  ## model parameters
  mode: "hard" # "soft" or "hard"
  nlayers: 6
  hidden: 32
  activation: "SiLU" # SiLU, ReLU, Identity, SIREN, GELU
  w0: 30


  ## wandb parameters
  wandb_group: "phase_2"
  wandb_project: "mini_pinn"
  wandb_entity: "guzelmen_msci_project"


  ## optimizer parameters
  lr_type: "cosine" # constant, linear, linear with cosine decay...
  constant_lr: 1e-4
  start_lr: 1e-5
  end_lr: 5e-4
  lr_warmup_epochs: 100
  min_lr: 1e-5  # Minimum LR for cosine decay

  ## loss parameters
  loss_strategy: "adaptive" # "fixed" or "adaptive"
  relative_weights: {"residual": 1.0, "bc_1": 1.0, "bc_2": 1.0}

  ## data parameters
  data_path: "data/64k_x_log_r0.pt"
  batch_size: 512

  ## training parameters
  stage: "train"
  epochs: 500
  save_every: 100
  weights_directory: "weights"
  